addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-cups

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" LINT_CHECK="1"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/partner-contact.git ${HOME}/partner-contact -b ${VERSION}
  - git clone https://github.com/OCA/account-fiscal-rule.git ${HOME}/account-fiscal-rule -b ${VERSION}
  - bzr branch lp:aeroo ${HOME}/aeroo_reports
  - git clone https://github.com/OCA/community-data-files.git ${HOME}/community-data-files -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install unicodecsv unidecode
  - travis_install_nightly
  - git clone https://github.com/aeroo/aeroolib.git ${HOME}/aeroolib
  - pushd ${HOME}/aeroolib; sudo python ./setup.py install; popd
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
